apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb
  labels:
    app.kubernetes.io/name: helloweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: helloweb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: helloweb
    spec:
      containers:
      - name: helloweb
        image: uweerikmartin/helloweb:latest
        env:
        - name: HELLOWEB_HEALTH_PORT
          value: "4000"
        resources:
          requests:
            memory: "16Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
        livenetssProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 3
          periodSeconds: 10