name: build
run-name: build ${{github.repository}} by ${{github.actor}}
on: [push, pull_request]

jobs: 
  build-multiarch:
    runs-on: ubuntu-latest

    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4

    - name: Evaluate Build Environment variables
      run: |
        sed -En 's/^go (.*)$/GO_VERSION=\1/p' go.mod >> $GITHUB_ENV
        sed -En 's/^.*=([0-9]*.[0-9]*.[0-9])$/VERSION=\1/p' VERSION >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3      

    - name: Build and Push Images without Manifests
      run: |
        export BUILDX_NO_DEFAULT_ATTESTATIONS=1
        docker buildx build --push --platform linux/amd64 --build-arg GO_VERSION=${{env.GO_VERSION}} --output "type=registry,name=${{env.REGISTRY}}/${{github.repository}},push-by-digest=true" -f build/Dockerfile . 2>&1 | tee out.txt
        sed -En 's/.*exporting manifest\s(sha256:[0-9a-f]*)\s.*/SHA_LINUX_AMD64=\1/p' out.txt >> $GITHUB_ENV

        docker buildx build --push --platform linux/arm64 --build-arg GO_VERSION=${{env.GO_VERSION}} --output "type=registry,name=${{env.REGISTRY}}/${{github.repository}},push-by-digest=true" -f build/Dockerfile . 2>&1 | tee out.txt
        sed -En 's/.*exporting manifest\s(sha256:[0-9a-f]*)\s.*/SHA_LINUX_ARM64=\1/p' out.txt >> $GITHUB_ENV

        docker buildx build --push --platform windows/amd64 --build-arg GO_VERSION=${{env.GO_VERSION}} --build-arg WINVER=ltsc2019 --output "type=registry,name=${{env.REGISTRY}}/${{github.repository}},push-by-digest=true" -f build/Dockerfile . 2>&1 | tee out.txt
        sed -En 's/.*exporting manifest\s(sha256:[0-9a-f]*)\s.*/SHA_WINDOWS_LTSC2019=\1/p' out.txt >> $GITHUB_ENV

        docker buildx build --push --platform windows/amd64 --build-arg GO_VERSION=${{env.GO_VERSION}} --build-arg WINVER=ltsc2022 --output "type=registry,name=${{env.REGISTRY}}/${{github.repository}},push-by-digest=true" -f build/Dockerfile . 2>&1 | tee out.txt
        sed -En 's/.*exporting manifest\s(sha256:[0-9a-f]*)\s.*/SHA_WINDOWS_LTSC2022=\1/p' out.txt >> $GITHUB_ENV

    - name: Build and Push multiplatform Manifest
      run: |
        docker buildx imagetools create --tag ${{env.REGISTRY}}/${{github.repository}}:${{env.VERSION}} ${{env.REGISTRY}}/${{github.repository}}@${{env.SHA_LINUX_AMD64}} ${{env.REGISTRY}}/${{github.repository}}@${{env.SHA_LINUX_ARM64}} ${{env.REGISTRY}}/${{github.repository}}@${{env.SHA_WINDOWS_LTSC2019}} ${{env.REGISTRY}}/${{github.repository}}@${{env.SHA_WINDOWS_LTSC2022}}