name: build
run-name: build ${{github.repository}} by ${{github.actor}}
on: [push, pull_request]

jobs: 
  # The “build” workflow 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4

    - name: Get Golang Version from go.mod file
      run: sed -En 's/^go (.*)$/GO_VERSION=\1/p' go.mod >> $GITHUB_ENV

    - name: Setup Go Enviroment
      uses: actions/setup-go@v4
      with:
        go-version: '${{ env.GO_VERSION }}' # The Go version to download (if necessary) and use.

    - run: go version

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Container Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/helloweb:amd64 build/Dockerfile        
    
    - name: Push to registry
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/helloweb:amd64                
