name: build
run-name: build ${{github.repository}} by ${{github.actor}}
on: [push, pull_request]

jobs: 
  build-multiarch:
    runs-on: ubuntu-latest

    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4

    - name: Setup Go Environment
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - name: Compile linux/amd64
      run:  GOOS=linux GOARCH=amd64   go build -o server-linux-amd64 cmd/server.go

    - name: Compile linux/arm64
      run:  GOOS=linux GOARCH=arm64   go build -o server-linux-arm64 cmd/server.go

    - name: Compile windows/amd64
      run:  GOOS=windows GOARCH=amd64 go build -o server.exe cmd/server.go

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3      

    - name: Build and push Docker linux/amd64
      run:  docker buildx build --push --platform linux/amd64 --build-arg=APPLICATION=server-linux-amd64 -t ${{ secrets.DOCKERHUB_USERNAME}}/helloweb:linux-amd64 -f build/Dockerfile.linux .

    - name: Build and push Docker linux/arm64
      run:  docker buildx build --push --platform linux/arm64 --build-arg=APPLICATION=server-linux-arm64 -t ${{ secrets.DOCKERHUB_USERNAME}}/helloweb:linux-arm64 -f build/Dockerfile.linux .

    - name: Build and push windows ltsc2019 image
      run: docker buildx build --push --platform windows/amd64 --build-arg=WINVER=ltsc2019 -t ${{ secrets.DOCKERHUB_USERNAME}}/helloweb:ltsc2019 -f build/Dockerfile.windows .

    - name: Build and push windows ltsc2022 image
      run: docker buildx build --push --platform windows/amd64 --build-arg=WINVER=ltsc2022 -t ${{ secrets.DOCKERHUB_USERNAME}}/helloweb:ltsc2022 -f build/Dockerfile.windows .

    - name: Build Manifest
      run: |
        docker buildx imagetools create ${{ secrets.DOCKERHUB_USERNAME}}/helloweb:latest ${{ secrets.DOCKERHUB_USERNAME}}/helloweb:linux-amd64 ${{ secrets.DOCKERHUB_USERNAME}}/helloweb:linux-arm64 ${{ secrets.DOCKERHUB_USERNAME}}/helloweb:ltsc2019 ${{ secrets.DOCKERHUB_USERNAME}}/helloweb:ltsc2022

#    - name: Push Manifest
#      run: |
#        docker manifest push --purge ${{ secrets.DOCKERHUB_USERNAME}}/helloweb:latest

