name: build
run-name: build ${{github.repository}} by ${{github.actor}}
on: [push, pull_request]

jobs: 
  build-multiarch:
    runs-on: ubuntu-latest

    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4

    - name: Evaluate GO Version
      run: sed -En 's/^go (.*)$/GO_VERSION=\1/p' go.mod >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push ltsc2022
      run: |
        docker buildx build --push --platform windows/amd64 --build-arg=WINVER=ltsc2022 -t ${{secrets.DOCKERHUB_USERNAME}}/helloweb:ltsc2022 -f build/Dockerfile .
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        build-args: GO_VERSION=${{env.GO_VERSION}},WINVER=ltsc2019
        platforms: linux/amd64,linux/arm64,windows/amd64
        file: build/Dockerfile
        tags: ${{secrets.DOCKERHUB_USERNAME}}/helloweb:latest
        provenance: false