name: build
run-name: build ${{github.repository}} by ${{github.actor}}
on: [push, pull_request]

jobs: 
  build-multiarch:
    runs-on: ubuntu-latest

    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4

    - name: Setup Go Environment
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - name: Compile windows/amd64
      run:  GOOS=windows GOARCH=amd64 go build -o server.exe cmd/server.go

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3      

    - name: Get Golang Version from go.mod file
      run: sed -En 's/^go (.*)$/GO_VERSION=\1/p' go.mod >> $GITHUB_ENV

    - name: Build and push Docker linux/amd64
      run:  |
        docker buildx build --push --platform linux/amd64 --iid tmp.txt --build-arg=GO_VERSION=${{ env.GO_VERSION }} -t ${{ secrets.DOCKERHUB_USERNAME}}/helloweb:linux-amd64 -f build/Dockerfile.linux .
        more tmp.txt


    - name: Build and push Docker linux/arm64
      run:  docker buildx build --push --platform linux/arm64 --build-arg=GO_VERSION=${{ env.GO_VERSION }} -t ${{ secrets.DOCKERHUB_USERNAME}}/helloweb:linux-arm64 -f build/Dockerfile.linux .

    - name: Build and push windows ltsc2019 image
      run: docker buildx build --push --platform windows/amd64 --build-arg=WINVER=ltsc2019 -t ${{ secrets.DOCKERHUB_USERNAME}}/helloweb:ltsc2019 -f build/Dockerfile.windows .

    - name: Build and push windows ltsc2022 image
      run: docker buildx build --push --platform windows/amd64 --build-arg=WINVER=ltsc2022 -t ${{ secrets.DOCKERHUB_USERNAME}}/helloweb:ltsc2022 -f build/Dockerfile.windows .

    - name: Build Manifest
      run: |
        docker buildx imagetools create --tag ${{ secrets.DOCKERHUB_USERNAME}}/helloweb:latest ${{ secrets.DOCKERHUB_USERNAME}}/helloweb:linux-amd64 ${{ secrets.DOCKERHUB_USERNAME}}/helloweb:linux-arm64 ${{ secrets.DOCKERHUB_USERNAME}}/helloweb:ltsc2019 ${{ secrets.DOCKERHUB_USERNAME}}/helloweb:ltsc2022